# -*- coding: utf-8 -*-
"""turing_patterns_static.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgvKLXK71MU3lULXV2ukCSZypY0FdTa_
"""

import os
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(100)

output_folder = "simulation_outputs"
os.makedirs(output_folder, exist_ok=True)

Da = 0.08
Dh = 0.16
dt= 1.0
dx= 1.0
N = 200
steps = 1000

feed_kill = [[0.035, 0.065], [0.022, 0.051], [0.040, 0.060], [0.025, 0.060], [0.014, 0.054]]
pattern_type = ['Spots', 'Bubbles', 'Maze_Labyrinth', 'Stripes', 'Spirals']

def Laplacian(z):
    return (np.roll(z, 1, axis=0) + np.roll(z, -1, axis=0) +
            np.roll(z, 1, axis=1) + np.roll(z, -1, axis=1) - 4*z) / (dx ** 2)

def run_turing_simulation(f, k, pattern_name):

    a = np.zeros((N, N))
    h = np.ones((N, N))

    r = 10
    cx, cy = N // 2, N // 2
    a[cx-r:cx+r, cy-r:cy+r] = 0.25
    h[cx-r:cx+r, cy-r:cy+r] = 0.50

    a += 0.02 * np.random.randn(N, N)
    h += 0.02 * np.random.randn(N, N)
    a = np.clip(a, 0, 1)
    h = np.clip(h, 0, 1)

    for _ in range(steps):
        dadt = Da * Laplacian(a) + h * a * a - (f + k) * a
        dhdt = Dh * Laplacian(h) - h * a * a + f * (1 - h)

        a += dt * dadt
        a = np.clip(a, 0, 1)

        h += dt * dhdt
        h = np.clip(h, 0, 1)

    plt.figure(figsize=(6,6))
    plt.imshow(a, cmap='inferno', vmin=0, vmax=1)
    plt.axis('off')
    plt.title(f'{pattern_name} (f={f}, k={k})')
    plt.colorbar(label='activator concentration')
    plt.tight_layout()

    filename = f"{pattern_name.lower()}.png"
    save_path = os.path.join(output_folder, filename)
    plt.savefig(save_path, dpi=300, bbox_inches='tight')

    print(f"done: {pattern_name}")

print("Starting all simulations...")
for (f_val, k_val), name in zip(feed_kill, pattern_type):
    run_turing_simulation(f_val, k_val, name)

print("all done")

