# -*- coding: utf-8 -*-
"""turing_patterns_animation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaxJqs3gAGuXjdOZkroI3h9KaFvUiCS0
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

Da = 0.08
Dh = 0.16
f = 0.035
k = 0.065
dt = 0.01
dx = 1.0
N = 200

out_dir = "simulation_outputs"
os.makedirs(out_dir, exist_ok=True)
video_path = os.path.join(out_dir, "turing_spots.mp4")

np.random.seed(42)

#Initialisation
a = np.zeros((N,N))
h = np.ones((N,N))
r = 10
cx, cy = N//2, N//2
a[cx-r:cx+r, cy-r:cy+r] = 0.25
h[cx-r:cx+r, cy-r:cy+r] = 0.50

#Random noise
a += 0.02 * np.random.randn(N,N)
h += 0.02 * np.random.randn(N,N)
a = np.clip(a, 0, 1, out=a)
h = np.clip(h, 0, 1, out=h)

def Laplacian (z):
  return (np.roll(z, 1, 0) + np.roll(z, -1, 0) + np.roll(z, 1, 1) + np.roll(z, -1, 1) - 4 * z) / dx**2

fig, ax = plt.subplots(figsize=(8,8))
ax.axis('off')
ax.text(0.02, 0.02, f'f={f}  k={k}', transform=ax.transAxes,
          color='white', fontsize=10, va='bottom')
im = ax.imshow(a, cmap='inferno', animated=True, vmin=0, vmax=1)
cbar = fig.colorbar(im, ax=ax, shrink=0.85, pad=0.04)
cbar.ax.tick_params(labelsize=10)
cbar.set_label("Activator Concentration ($a$)", fontsize=12, labelpad=15)
title_text = ax.set_title("Step: 0 | Avg Activator: 0.000", fontsize=14, pad=20)

def step (frame):
  global h, a
  for _ in range(30):
    haa = h*a*a
    dadt = Da*Laplacian(a) + haa -(f+k)*a
    dhdt = Dh*Laplacian(h) - haa + f*(1-h)
    a += dt * dadt
    h += dt * dhdt
    a = np.clip(a, 0, 1, out=a)
    h = np.clip(h, 0, 1, out=h)
  im.set_array(a)

  avg_activator = np.mean(a)
  title_text.set_text(f"Step: {frame * 30} | Avg Activator: {avg_activator:.3f}")

  return [im, title_text]

ani = animation.FuncAnimation(
      fig, step, frames = 500, interval = 20, blit = False
  )

ani.save(video_path, writer = 'ffmpeg', fps = 30, dpi = 150)
plt.show()

